travis:
  secure:
    BINSTAR_TOKEN: T/PMJKRlNS/IZAXdx/od55u4YprMBE1RmTdO0R9Z97j2T+aMPiwcJuUF2GhbAstwEIHGd1cmXA+DYEuTXw7UH8ols+htGZkPJkDRYcV9i4d4f8rl+xQ0G9G+Pot68yTeAbOeOPZIialQJi/ufVeCLg0gNgiaX89IlX752faqdRVbHFHb6mtM01SbvDpnmzGYj6MeYf3ZMIs2gjkDHs99pgAVtTSqDG2ZmMqrUT9qEdWpj2zmyrZAfvSI3qHN6v3ZBXyMcPg0AvlCLJKy9pJzx5eYp6JWYhXGg1uFeKdvIc+Pc33CvwV24ZLzhv8Axgk/ga1vCcONa3clrewC9z/XIP48d7up/uZhcLK2Zv3KXk1bxOsadzjFu3y6PHsMVixeYSh4167EEWrlM8pW0xshwD4G8K9LQZKOPkcwqsgjpI5/epwmNooUvmPgZnxQQ/xe1F3Oy8LqmxQBtMRVYFUnDscSNNv34CiGoMHvdOjFJ2MAnwmdJqADvtUk65E/90NPCjfJzuWNo0ozgLpldJ9HlN26d/CSpoYV9zegM0aqq8r3ZiORuHrp2uUiEajn9MJE5uNIUhiLOXjUx4rZSomliRmQYo0Z1Jewndwvd1dqbw14qKYhyRXKDmekHJgc24g1n1SWh9WKrMJKd2WSH/BnTcmrGYa7Nr6tzsiV963WsRg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
